botshot/webchat/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    # url(r'(?P<uid>[0-9]+)', view=webchat, name='webchat'),
    url(r'^$', view=webchat, name='webchat'),
    url(r'^logout/?$', view=do_logout, name='do_logout'),
    url(r'^last_change/$', view=get_last_change, name='last_change')
]

botshot/webchat/forms.py
from django import forms


class MessageForm(forms.Form):

    message = forms.CharField(
        label='Message',
        max_length=1024,
        widget=forms.TextInput(attrs={'placeholder': 'Type message here'})
    )

botshot/webchat/views.py
import json
from datetime import datetime

from django.conf import settings
from django.db.models import Max
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect

from botshot.models import ChatMessage
from botshot.webchat.interface import WebchatInterface
from .forms import MessageForm
import logging


def webchat(request):
    if request.method == 'POST':
        if not request.POST.get('message'):
            print("Error, message not set in POST")
            return HttpResponse(400)

        if 'webchat_id' not in request.session:
            webchat_id = WebchatInterface.make_webchat_id()
            request.session['webchat_id'] = webchat_id

        interface = WebchatInterface()
        is_ok = interface.webhook(request)
        return JsonResponse({'ok': True}) if is_ok else HttpResponse(400)

    if 'webchat_id' in request.session:
        messages = _get_webchat_id_messages(request.session['webchat_id'])
    else:
        messages = []
        welcome_msg = settings.BOT_CONFIG.get(
            'WEBCHAT_WELCOME_MESSAGE',
            'Hi there, this is the default greeting message!'
        )
        if welcome_msg:
            default_message = ChatMessage()
            default_message.type = ChatMessage.MESSAGE
            default_message.text = welcome_msg
            default_message.time = datetime.now()
            default_message.is_user = False
            messages.append(default_message)

    context = {
        'messages': messages,
        'form': MessageForm,
        'timestamp': datetime.now().timestamp(),
        'user_img': settings.BOT_CONFIG.get('WEBCHAT_USER_IMAGE', 'images/icon_user.png'),
        'bot_img': settings.BOT_CONFIG.get('WEBCHAT_BOT_IMAGE', 'images/icon_robot.png')
    }
    return render(request, 'botshot/webchat/index.html', context)


def do_logout(request):
    if 'webchat_id' in request.session:
        del request.session['webchat_id']
    return redirect('webchat')


def _get_webchat_id_messages(webchat_id):
    return ChatMessage.objects.filter(conversation__raw_conversation_id=webchat_id).order_by('time')


def get_last_change(request):
    if 'webchat_id' not in request.session:
        max_timestamp = 0
    else:
        webchat_id = request.session['webchat_id']
        max_timestamp = _get_webchat_id_messages(webchat_id).aggregate(Max('time')).get('time__max')
        max_timestamp = max_timestamp.timestamp() if max_timestamp else 0
    return JsonResponse({'timestamp': max_timestamp})

botshot/webchat/templates/botshot/webchat/index.html
<!DOCTYPE html>
{% load staticfiles %}
{% load botshot_extras %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/webchat.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simplebar/2.6.1/simplebar.min.css">
    <title>Botshot chatbot</title>
    <noscript>
        <style>
        [data-simplebar] {
            overflow: auto;
        }
        </style>
    </noscript>
</head>
<body>
<div id="header">
    <h1>Messages</h1>
    <div id="button_logout" onclick="logout()">Log out</div>
</div>
<div id="list_wrap" data-simplebar>
    <div id="list">
        {% for m in messages %}
            <div class="message-wrap {% if m.is_user %} user-wrap {% else %} bot-wrap {% endif %}">
                <div class="time">[{{ m.time }}]</div>

                <img class="circle-image" src="{% if m.is_user %}{% static user_img %}{% else %}{% static bot_img %}{% endif %}"
                     onerror='this.onerror=null; this.src="https://placehold.it/100x100"'/>

                {% if m.type == 'message' %}
                    {% if m.text %}
                    <div class="bubble">
                        <span class="text">{{ m.text }}</span>
                    </div>
                    {% endif %}

                    {% if m.response_dict.buttons != None %}
                        <div class="clearfix"></div>
                        <div class="buttons">
                            {% for b in m.response_dict.buttons %}
                                {% if b.type == 'web_url' %}
                                    <button onclick="gourl('{{ b.url }}')">{{ b.title }}</button>
                                {% elif b.type == 'postback' %}
                                    <button onclick="postback('{{ b.title }}', '{{ b.payload | json | escapejs }}')">
                                        {{ b.title }}
                                    </button>
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% endif %}

                    {% if m.response_dict.quick_replies != None %}
                        <div class="clearfix"></div>
                         <div class="quick-replies">
                            {% if forloop.last %}
                                {% for b in m.response_dict.quick_replies %}
                                        {% if b.payload %}
                                            <button onclick="postback('{{ b.title }}', '{{ b.payload | json | escapejs}}')">
                                                {{ b.title }}
                                            </button>
                                        {% else %}
                                            <button onclick="quickreply('{{ b.title }}')">
                                                {{ b.title }}
                                            </button>
                                        {% endif %}
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endif %}

                    {% if m.response_dict.elements %}
                        <!-- Horizontal (Carousel) template -->
                        <div class="template-message carousel-template" data-simplebar>
                        {% for e in m.response_dict.elements %}
                            <div class="template-element carousel-element">
                                <img src="{{ e.image_url }}"
                                     onerror="this.onerror=null;this.src='https://placehold.it/250x150'"/>
                                <h3>{{ e.title }}</h3>
                                <p>{{ e.subtitle | default_if_none:"" }}</p>
                                <div class="buttons">
                                {% for b in e.buttons %}
                                    {% if b.url %}
                                        <button onclick="gourl('{{ b.url }}')">{{ b.title }}</button>
                                    {% elif b.payload %}
                                        <button onclick="postback('{{ b.title }}', '{{ b.payload | json | escapejs }}')">
                                            {{ b.title }}
                                        </button>
                                    {% else %}
                                        <button onclick="alert('Button type not supported in web chat')">
                                        {{ b.title }}
                                        </button>
                                    {% endif %}
                                {% endfor %}
                                </div>
                            </div>
                        {% endfor %}
                        </div>

                    {% endif %}

                {% elif m.message.attachment.payload.template_type == 'list' %}

                    <!-- Vertical (List) template -->
                    <div class="template-message list-template">
                    {% for e in m.message.attachment.payload.elements %}
                        <div class="template-element">
                            <img src="{{ e.image_url }}"
                                 onerror="this.onerror=null;this.src='https://placehold.it/250x150'"/>
                            <h3>{{ e.title }}</h3>
                            <p>{{ e.subtitle | default_if_none:"" }}</p>
                            <div class="buttons">
                                {% for b in e.buttons %}
                                    {% if b.url %}
                                        <button onclick="gourl('{{ b.url }}')">{{ b.title }}</button>
                                    {% elif b.payload %}
                                        <button onclick="postback('{{ b.title }}', '{{ b.payload | json | escapejs }}')">
                                            {{ b.title }}
                                        </button>
                                    {% else %}
                                        <button onclick="alert('Button type not supported in web chat')">
                                        {{ b.title }}
                                        </button>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                {% elif m.type == 'postback' %}
                    <div class="bubble bubble-postback">
                        <span class="text">{{ m.text }}</span>
                    </div>
                {% elif m.type == 'message' %}
                    <div class="bubble">
                        <span class="text">{{ m.text }}</span>
                    </div>
                {% else %}
                    <div class="bubble">
                        <span class="text">{{ m.type }}: {{ m.text }}</span>
                    </div>
                {% endif %}
            <div class="clearfix"></div>
        </div>
        {% endfor %}
    </div>
</div>
<div id="footer">
    <form id="form_msg" autocomplete="off">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Send">
</form>
</div>
</body>

<script src="{% static 'scripts/jquery-3.3.1.min.js' %}"></script>

<script type="text/javascript">
    function quickreply(text) {
        console.log("Quick reply");
        $.ajax({
                url: document.URL,
                type: 'POST',
                dataType: 'json',
                data: {
                    message: text,
                    csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value
                }
            });
    }
    function gourl(url) {
        window.open(url, '_blank');
    }

    function postback(text, payload) {
        console.log("Postback");
        console.log(payload);
        $.ajax({
            url: document.URL,
            type: 'POST',
            dataType: 'json',
            data: {
                message: text,
                payload: payload,
                csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value
            }
        });
    }

    $(document).ready(function () {
        $('#form_msg').submit(function (e) {
            e.preventDefault();
            var txt = $('#id_message');
            $.ajax({
                url: document.URL,
                type: 'POST',
                dataType: 'json',
                data: {
                    message: txt.val(),
                    csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value
                }
            });
            txt.val("")
        })
    });

    var last_change = {{ timestamp }};
    var POLL_INTERVAL_MS = 2000;
    $(window).on('load', function() {
        $("#list_wrap").scrollTop($("#list_wrap").prop("scrollHeight"));
        setInterval(refresh, POLL_INTERVAL_MS);
    });

    function refresh() {
        $.get("{% url 'last_change' %}", {}, function (data) {
            var timestamp = data['timestamp'];
            if (timestamp > last_change) {
                console.log('Refreshing');
                // change occurred, reload messages
                $('#list').load(document.URL + ' #list');
                last_change = timestamp;
                $("#list_wrap").animate({scrollTop: $("#list_wrap").prop("scrollHeight")}, "slow");
            }
        });
    }

    function logout() {
        window.location = "{% url 'do_logout' %}"
    }
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/simplebar/2.6.1/simplebar.min.js"></script>